### ISSUE TITLE
Hour off for Hawaii Standard time

### ISSUE THREAD

**Issue by rcrath** [simonwiles/cinnamon_applets#16]
The stock cinnamon clock applet shows Hawaii time properly, (the system clock setting) but the world clock applet is an hour behind, I think because it is computing daylight savings time, which we do not have in Hawaii.  Otherwise it is a fantastic applet, just can't replace my stock clock with it yet.  If the image works, the stcok clock is on the right side of the panel with the correct time, the world clock on the left with the hour-off time.
![screenshot-area-2014-06-13-192549](https://cloud.githubusercontent.com/assets/944636/3277600/7053ce2e-f384-11e3-805d-df6199ada990.png)

**Comment by simonwiles** [comment]
I think this issue should be closed now -- if you're still having problems, please feel free to re-open it!

**Comment by rcrath** [comment]
@simonwiles thanks! looks good so far.
