### ISSUE TITLE
Does not handle 24 hour time

### ISSUE THREAD

**Issue by akumria** [simonwiles/cinnamon_applets#22]
Hi,

With the standard clock, I can check configure the Date and Time settings and select 'use 24h clock'.

Unfortunately when using the World clock, that settings is not listened to.

Thanks,
Anand

**Comment by zfjagann** [comment]
Use `%T` in your custom date format.

Use [foragoodstrftime.com](http://www.foragoodstrftime.com/) to try out different formats.

**Comment by akumria** [comment]
That also means you have to specify a custom date format _and_ the time format for world clocks.

Very cumbersome.

**Comment by simonwiles** [comment]
I think the settings for the world clocks have to be independent of the settings for the main clock.  Yes, it means that if you want them to be the same, you have to set them to be the same.

**Comment by akumria** [comment]
I'm (was) perfectly happy for how things are working, I'd just rather have 24 hour time rather than AM/PM.

But as you've labelled this invalid, I'll fork and adapt a version that uses a single location; I can't (personally) conceive of a use case where have the time displayed differently is particularly useful.

**Comment by simonwiles** [comment]
I'm sorry, did I offend you?  In my screenshot, as an example, you'll notice that I have the day of the week in parentheses after the time for the world clocks, for those cases where another timezone is a day ahead or behind.  Is it really so difficult to set the time for the world clocks the way you want it when you first install the applet?
