### ISSUE TITLE
Global times not displaying correctly

### ISSUE THREAD

**Issue by zfjagann** [simonwiles/cinnamon_applets#24]
Freshly installed build of 1.1 from the cinnamon spices page.

I added UTC to the list of world clocks I'd like to display, but it doesn't appear in the list.

I also tried this with `Europe/London` and it didn't work either.

![Screenshot](http://i.imgur.com/mEfuEAH.png)

It's probably worth noting that I havne't restarted cinnamon since I installed the applet. Maybe cinnamon restart is required to run correctly?

**Comment by zfjagann** [comment]
I tried restarting cinnamon (`cinnamon --replace`) just to see what would happen and it caused different issues (#25), and did not fix the problem.

**Comment by gsmcmullin** [comment]
I have this same problem on LMDE 2 (Cinnamon 2.6)

**Comment by thenitai** [comment]
Just installed and still not working...

**Comment by simonwiles** [comment]
i haven't been able to replicate this at all, with any version of Linux Mint or LMDE (currently using Cinnamon 2.6.13).  Can anyone provide more information?

**Comment by thenitai** [comment]
Sure. What do you need? I just install Cinnamon 2.6.x yesterday on top of
Ubuntu 15.04.

On Wed, Aug 26, 2015 at 6:22 PM, Simon Wiles <notifications@github.com>
wrote:

> i haven't been able to replicate this at all, with any version of Linux
> Mint or LMDE (currently using Cinnamon 2.6.13). Can anyone provide more
> information?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simonwiles/cinnamon_applets/issues/24#issuecomment-135215923>
> .
>



-- 
See for yourself how easy it is to manage files today. Join the revolution!

Razuna - Hosted Digital Asset Management Solution
http://www.razuna.com/

Razuna - Open Source Digital Asset Management
http://www.razuna.org/

Twitter - http://twitter.com/razunahq
Support Platform - http://help.razuna.com

**Comment by simonwiles** [comment]
that could be relevant, thanks.  I've just released an update through cinnamon-spices; please let me know if it solves the problem.

**Comment by thenitai** [comment]
Hi,

Thank you for the fast reply. Though, I see other issues now:

1) There are now two instances of the clock available. Though, one doesn't
do anything.

![selection_017](https://cloud.githubusercontent.com/assets/372121/9524944/da06e08a-4c9e-11e5-9101-932ec82020d1.png)

2) Not an "issue" per se, more a design thing. But world times have no
padding. Might I suggest to add some padding?

![menu_016](https://cloud.githubusercontent.com/assets/372121/9524914/ba4c1972-4c9e-11e5-90d2-5d2ae75c0678.png)

3) All my world clock settings were removed during the update.

Thank you again for the fast update. Really like your applet.

On Wed, Aug 26, 2015 at 10:41 PM, Simon Wiles notifications@github.com
wrote:

> that could be relevant, thanks. I've just released an update through
> cinnamon-spices; please let me know if it solves the problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/simonwiles/cinnamon_applets/issues/24#issuecomment-135288850
> .

## 

See for yourself how easy it is to manage files today. Join the revolution!

Razuna - Hosted Digital Asset Management Solution
http://www.razuna.com/

Razuna - Open Source Digital Asset Management
http://www.razuna.org/

Twitter - http://twitter.com/razunahq
Support Platform - http://help.razuna.com
