### ISSUE TITLE
Clock does not update

### ISSUE THREAD

**Issue by Pablohn26** [simonwiles/cinnamon_applets#30]
After latest upgrade on Fedora 24 clock does not update. It seems a problem only with this applet, as you can see default clock applet works as expected. Right one is World Clock Calendar (it is stopped) and left one is Cinnamon clock. 

os: Fedora 24
version: Cinnamon 3.2.2

![image](https://cloud.githubusercontent.com/assets/1228418/21098295/cfdcef66-c068-11e6-9312-3c10dc6d97ae.png)

**Comment by dstromberg** [comment]
I'm seeing this problem on Mint 18.1 (Cinnamon 3.2.7).

**Comment by nicoma** [comment]
same issue here :  #31

**Comment by sphh** [comment]
The simple pull request from #28 solves both this and problem in #31.

**Comment by dajusc** [comment]
@simonwiles It would be really great if you would fix this! :) 
I loved using your worldclock on Linux Mint Cinnamon until this issue broke it several months ago! :(

**Comment by simonwiles** [comment]
I believe this issue has been solved for some time (see [linuxmint/cinnamon-spices-applets/issues/285](https://github.com/linuxmint/cinnamon-spices-applets/issues/285)) -- are you using the latest version?

**Comment by dajusc** [comment]
Yes, that was the problem. Seems to work now, thx! :)
